# Tâche 5 : Symmetry

Etudiez l’effet de 3 éléments de symétrie différents (pas l’identité), chacun pour 1 atome différent. Repésentez-les.

## Introduction

Les opérations de symétrie sont constituées d'une matrice de rotation (Rot) 3x3 et un vecteur de translation (tau) 3x1 tel que :
Rot * (x, y, z)^T + tau    
Nous pouvons dès lors étudier la position initiale d'un atome et sa position finale (après l'opération de symétrie).

Pour illustrer ces opérations, nous allons étudier 3 opérations de symmétrie appliquées à un atome différent du ZnCoBi : la symétrie d'inversion, la rotation d'ordre 2 et enfin la réflexion.

Une première représentation de la structure du ZrCoBi est donnée dans sa maille conventionnelle. 

In [105]:
import numpy as np
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifWriter
from pymatgen.io.cif import CifParser
from IPython.display import FileLink
from IPython.display import display
from IPython.display import Image
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

from jupyter_jsmol import JsmolView
from jupyter_jsmol.pymatgen import quick_view

mp_key = "XmhOs3iaP3YopOzhwHSd0LHcduZB1r1h"
mp_id = "mp-31451"
material_name = "ZrCoBi"

In [107]:
# Utilisation du fichier cif car le code donné ne fonctionnait pas pour mon matériau
parser = CifParser("ZrCoBi.cif")

# Structure du matériau
prim_struc = parser.get_structures()[0]
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()

# Symétrie du matériau
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()


# Représentation de la structure dans sa maille conventionnelle
#Turquoise = Zr
#Rose = Co
#Mauve = Bi
view = quick_view(conv_struc)
display(view)

/tmp/ipykernel_1545010/1337243311.py:5: DeprecationWarning:         `get_structures` is deprecated!
        get_structures is deprecated and will be removed in 2024. Use parse_structures instead.The only difference is that primitive defaults to False in the new parse_structures method.So parse_structures(primitive=True) is equivalent to the old behavior of get_structures().
  prim_struc = parser.get_structures()[0]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

## 1. Symétrie d'inversion de l'atome 3 (Bi)

La symétrie d'inversion est une symétrie ponctuelle. Elle se fait selon un centre donné et inverse la chiralité.

In [110]:
# Numéro de l'atome choisi
i_atom = 3

# Numéro du type de symmétrie choisie
i_symmop = 2

print("\n-----------------------------------------")
print("Symétrie d'inversion de centre (0, 0, 0):")
print("-----------------------------------------\n")


print("\nMatrice de rotation (Rot) et vecteur de translation (tau):\n")
symmop = symmops[i_symmop - 1]
print(symmop)

pos_init = conv_struc.sites[i_atom -1].frac_coords
print("\nPosition initiale de l'atome 3 :", pos_init)


pos_final = symmop.operate(pos_init)
print("\nPosition finale de l'atome 3 :", pos_final)


# Représentation
view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('select Zr; color lightsalmon')
view.script('select Co; color gold')
view.script('select Bi; color palegreen')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')




-----------------------------------------
Symétrie d'inversion de centre (0, 0, 0):
-----------------------------------------


Matrice de rotation (Rot) et vecteur de translation (tau):

Rot:
[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]

Position initiale de l'atome 3 : [0.5 0.  0.5]

Position finale de l'atome 3 : [ 0.  -0.5 -0.5]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

## 2. Symétrie de rotation d'ordre 2 de l'atome 2 (Co)

La rotation d'ordre 2 (180°) est une symétrie ponctuelle. Elle se fait autour d'un axe et conserve la chiralité.

In [112]:
# Numéro de l'atome choisi
i_atom = 2

# Numéro du type de symmétrie choisie
i_symmop = 3

print("\n-------------------------------")
print("Symétrie de rotation d'ordre 2:")
print("-------------------------------\n")


print("\nMatrice de rotation (Rot) et vecteur de translation (tau):\n")
symmop = symmops[i_symmop - 1]
print(symmop)

pos_init = conv_struc.sites[i_atom -1].frac_coords
print("\nPosition initiale de l'atome 2 :", pos_init)

pos_final = symmop.operate(pos_init)
print("\nPosition finale de l'atome 2 :",pos_final)

# Représentation
view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('select Zr; color lightsalmon')
view.script('select Co; color gold')
view.script('select Bi; color palegreen')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')


-------------------------------
Symétrie de rotation d'ordre 2:
-------------------------------


Matrice de rotation (Rot) et vecteur de translation (tau):

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]

Position initiale de l'atome 2 : [0.  0.5 0.5]

Position finale de l'atome 2 : [ 0.  -0.5  0.5]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

## 3. Symétrie de réflexion de l'atome 11  (Zn)

La réflexion est une symétrie ponctuelle. Elle se fait par rapport à un plan mirroir (en vert sur l'image) et inverse la chiralité.

In [114]:
# Numéro de l'atome choisi
i_atom = 11

# Numéro du type de symmétrie choisie
i_symmop = 6

print("\n---------------------------------------------")
print("Symétrie de réflexion selon un plan mirroir :")
print("---------------------------------------------\n")


print("\nMatrice de rotation (Rot) et vecteur de translation (tau):\n")
symmop = symmops[i_symmop - 1]
print(symmop)

pos_init = conv_struc.sites[i_atom -1].frac_coords
print("\nPosition initiale de l'atome 11 :", pos_init)

pos_final = symmop.operate(pos_init)
print("\nPosition finale de l'atome 11 :", pos_final)

# Représentation
view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('select Zr; color lightsalmon')
view.script('select Co; color gold')
view.script('select Bi; color palegreen')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')


---------------------------------------------
Symétrie de réflexion selon un plan mirroir :
---------------------------------------------


Matrice de rotation (Rot) et vecteur de translation (tau):

Rot:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.]

Position initiale de l'atome 11 : [0.5 0.  0. ]

Position finale de l'atome 11 : [0.  0.5 0. ]


JsmolView(layout=Layout(align_self='stretch', height='400px'))